### ISSUE TITLE
Signature of "request"

### ISSUE THREAD

**Issue by ioneyed** [akamai/edgeworkers-examples#12]
I cannot find any documentation on the signature of the "request" parameter that is passed into the lifrecycle methods.

Can you supply the signature of the parameter?

What are the limitations currently on the edge-workers? I cannot find the documentation that lists what functionality isn't there such as subrequests/etc.

**Comment by dctheobald** [comment]
Hey @ioneyed  - good to talk to you again :-)
Here are the docs you were looking for - 
[Request Object docs](https://learn.akamai.com/en-us/webhelp/edgeworkers/edgeworkers-user-guide/GUID-8BB264F4-2D50-4CBA-B297-61A87189ADE6.html)

Current system limits can be found [here](https://learn.akamai.com/en-us/webhelp/edgeworkers/edgeworkers-user-guide/GUID-F709406E-2D67-4996-B619-91E90F04EDF2.html)

As far as feature roadmap, I can share that with you directly over email if that's okay?
