### ISSUE TITLE
Support for WASM on Edgeworkers

### ISSUE THREAD

**Issue by CMoore-Darwinium** [akamai/edgeworkers-examples#170]
I notice that EdgeWorkers runs on a V8 environment with WASM support explicitly disabled (see: https://techdocs.akamai.com/edgeworkers/docs/specifications).
 
However, I also noticed that WASM is mentioned in your FAQ: https://techdocs.akamai.com/edgeworkers/docs/edgeworkers-javascript-code so I was wondering if there were any plans to open this functionality up?

**Comment by dctheobald** [comment]
Hi @CMoore-Darwinium - WASM is being discussed for EdgeWorkers' future roadmap, but there are no plans at the current time to support WASM.
