### ISSUE TITLE
EdgeWorkers - external calls

### ISSUE THREAD

**Issue by schneiderlazar** [akamai/edgeworkers-examples#22]
Hi all,

trying to work with EdgeWorkers to solve a problem on hand:

•	We have an application that is available in 2 datacenters
•	1 of the data centers is not super stable and we want an automatic "instant" failover
•	Of course there is a standard behavior for that in DSA – BUT the challenge is that this app is firing various requests where some of them might be failing and some of them won’t. so if we only failover for some requests the app is going to chaos state
•	Of course there is also GTM and application loadbalancer – but the problem there is that checking if the app is working fine is only possible post login/ADFS etc. so it is not a single http call – hence this will also not work
•	What we finally ended up with is doing a robot that can check the app functions and is then triggering the failover – working fine, but has the problem that property activation takes 10 mins and failover should be more or less instant
•	So what we did wondered is – can we use an Edgeworker to check for a status and do a redirect of requests to a maintenance page before the actual failover gets active
 
A simple idea was to have some sort of configuration "somewhere" (in our case we'd probably have a NetStorage file that can be queried and update) that is queried by the EdgeWorker and then a redirect to a maintenance page happens.

Below is some sample code that I tried - but EdgeWorkers throws an exception saying code is not accepted.

I think the code will not hit limitations as the request to Nestorage is very fast (25-30 ms) - but apparently Node syntax is not supported.

Can you advise on any options to implement such a scenario since EdgeKV is not an option yet?

Thanks,
Johannes

```
var options = {
  host: 'SOMEHOST',
  port: 80,
  path: 'SOMEPATH',
  method: 'GET'
};
 
var req = http.request(options, function(res) {
 
     // callback invoked when response is received
  res.setEncoding('utf8');
 
  res.on('data', function (chunk) {
 
                if(chunk == 'failover') {
                               // redirect to new host
                               request.respondWith(302, {
                                               'Location' : [ 'SOMEREDIRECT']
                               }, '');
                }
 
      });
});
 
req.on('error', function(e) {
  // not sure how to do error logging on edge workers – see your comment
});
 
req.end();
```

**Comment by dctheobald** [comment]
Hi @schneiderlazar - i've addressed these questions in a direct mail so going to close this issue in the repo.  Thanks!

**Comment by Gr8z** [comment]
@dctheobald Is it not possible to make calls to third-party APIs? The URLs have to be within the network?
