### ISSUE TITLE
Clarity on Request setVariable method

### ISSUE THREAD

**Issue by fabriziomarmitt** [akamai/edgeworkers-examples#24]
Hello! 

By studying the doc https://learn.akamai.com/en-us/webhelp/edgeworkers/edgeworkers-user-guide/GUID-C05789C6-9DFE-430F-8DD9-A50389AFF748.html is not clear to me how does setVariable works

**My Use Case**

In my PM I've created the variable `PMUSER_MyVariable` and in my code, I've done

```
//PMUSER_MyVariable: "MyValue" -> Default Value defined at PM
if(someConditionIsTrue) {
   request.setVariable('PMUSER_MyVariable',’MyNewValue’); // Expected new Value
}
```

Expected Result: After request "A" set `PMUSER_MyVariable` to `MyNewValue`, a new request B, when performing `request.getVariable('PMUSER_MyVariable')` would result  `MyNewValue`. AND, when check the value in PM, PMUSER_MyVariable should be `MyNewValue`

Actual Result: Request B `request.getVariable('PMUSER_MyVariable')` results  `MyValue`. AND when check the value in PM, PMUSER_MyVariable is `MyValue`.  [In other words, setVariable didn't work as I would expect].

**Question**

- Is request.setVariable a persistent operation among all requests? Or it is a request-lived operation?
- If setVariable is a request-lived operation, rather than a persistent operation, is there an alternative to persist data in edge-workers?

**Why do I need to persist data in EW: Ask for advice**

A change in PM or EW takes at least 10 minutes to activate and this time is not acceptable for my scenario. I would expect using setVariable to check some conditions, and when these conditions are true, change the behavior of all subsequent requests.

**Comment by devrel-edgeworkers** [comment]
Fabrizio,

PMUSER_ variables are “request-scoped”, therefore any interaction with the PMUSER_ variable in an EdgeWorker (setVariable, addVariable, getVariable)  is also request scoped.

There will be a solution entering tech-preview mid-October that will allow the persisting of data on the Akamai network making it available across requests. Let me know if you would like to learn more, I can set up a meeting with the Product team who can share the solution details with you.

Thanks,

Steve…

Steven Scian, CISSP
Senior Product Engineer
[signature_559845219]



 Office:   +1.613.670.8422
     Cell:   +1.613.866.2589
     Fax:   +1.613.670.8401

Akamai Technologies Canada
4th Floor, 343 Preston Street
Ottawa, Ontario Canada
K1S-1N4

**Comment by fabriziomarmitt** [comment]
Well yes I would like to know more about it
